<!doctype html>
<meta charset="utf-8">
<h2>Create a student</h2>
<form method="post" action="create.php">
    <div>
        <label>Name</label>
        <input type="text" name="name">
    </div>
    <div>
        <label>Surame</label>
        <input type="text" name="surname">
    </div>
    <div>
        <label>Sex</label>
        <input type="text" name="sex">
    </div>
    <div>
        <label>Group Id</label>
        <input type="text" name="group_id">
    </div>
    <div>
        <label>Email</label>
        <input type="text" name="email">
    </div>
    <div>
        <label>Score</label>
        <input type="text" name="score">
    </div>
    <div>
        <label>Birth Year</label>
        <input type="text" name="birthYear">
    </div>
    <div>
        <label>Local</label>
        <input type="text" name="local">
    </div>
    <input type="submit" value="Submit" name="submit">
</form>
